{{- if .Values.workers.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-flower
  labels:
    app: {{ template "airflow.name" . }}
    component: flower
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.flower.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.flower.service.type | default .Values.airflow.service.type }}
  selector:
    app: {{ template "airflow.name" . }}
    component: flower
    release: {{ .Release.Name }}
  ports:
    - name: flower
      protocol: TCP
      port: {{ .Values.flower.service.port }}
      targetPort: 5555
{{- end }}
